version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven"
      - yum update -y
      - yum install -y maven

  build:
    commands:
      - cd service-queue-aws
      - mvn clean package -DskipTests

artifacts:
  files:
    - service-queue-aws/target/service-queue-aws-1.0.0.jar
  discard-paths: yes
